#!/bin/bash
GREEN="\033[0;32m"
RED="\033[31m"
NC="\033[0m"

# CHECKING IF DOCKER IS RUNNING 


DRUN=`ps aux | grep dockerd | grep -v grep`
if [ -z "$DRUN" ]; then
  echo -e "[${RED}x${NC}] Docker is not running "
  echo -n "Do you want to run docker (y/n) "
  read answer
    if [ "$answer" != "${answer#[Yy]}" ] ;then
      echo "Proceding to start docker"
      sudo dockerd > /dev/null 2>&1 &
    else
      echo "Selected no, closing... "
      exit 1
    fi
else
  echo -e "[${GREEN}✓${NC}] Docker is running"
  echo -n "Do you want to stop docker (y/n) "
  read answer
    if [ "$answer" != "${answer#[Yy]}" ] ;then
      echo "Proceding to stop docker..."
      sudo pkill -f docker
    else
      echo "Selected no, closing... "
      exit 1
    fi
fi



